window.enemyData = [
    {
        "id": "C000",
        "name": "ヒューマノイド型UMA",
        "emoji": "👽",
        "image": "assets/uma_humanoid_final_03.jpg",
        "hp": 16,
        "exp": 3,
        "level": 1,
        "encounterType": "shadow"
    },
    {
        "id": "C001",
        "name": "モスマン",
        "emoji": "👻",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "怪異/ひと型",
        "region": "目が赤い・毛が生えている設定",
        "size": "",
        "description": "",
        "image": "assets/uma_mothman.png",
        "encounterType": "shadow"
    },
    {
        "id": "C002",
        "name": "モンキーマン",
        "image": "assets/uma_monkey_man.png",
        "emoji": "👾",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "ひと型",
        "region": "100人以上が目撃などの設定",
        "size": "",
        "description": "",
        "encounterType": "beast"
    },
    {
        "id": "C003",
        "name": "グレイ",
        "emoji": "👽",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "宇宙人",
        "region": "小柄な人間くらい・体は灰色",
        "size": "",
        "description": "",
        "image": "assets/uma_gray.png",
        "encounterType": "shadow"
    },
    {
        "id": "C004",
        "name": "キシュテム・ドワーフ",
        "image": "assets/uma_kistem_dwarf.png",
        "emoji": "🧚",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "小人",
        "region": "0.5",
        "size": "頭が大きい赤ちゃんのよう",
        "description": "",
        "encounterType": "shadow"
    },
    {
        "id": "C005",
        "name": "リザードマン",
        "emoji": "🦍",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "獣人",
        "region": "トカゲのような姿",
        "size": "",
        "description": "",
        "image": "assets/uma_lizardman.png",
        "encounterType": "beast"
    },
    {
        "id": "C006",
        "name": "ドーバー・デーモン",
        "emoji": "👻",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "怪異/ひと型",
        "region": "1.2",
        "size": "細い手足・長いゆび",
        "description": "",
        "image": "assets/uma_dover_demon.png",
        "encounterType": "shadow"
    },
    {
        "id": "C007",
        "name": "フォウク・モンスター",
        "image": "assets/uma_fouke_monster.png",
        "emoji": "🦍",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "獣人",
        "region": "2",
        "size": "長い毛・におい設定",
        "description": "",
        "encounterType": "beast"
    },
    {
        "id": "C008",
        "name": "ノーム",
        "image": "assets/uma_gnome.png",
        "emoji": "🧚",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "小人",
        "region": "1",
        "size": "ヨーロッパなどの伝承系",
        "description": "",
        "encounterType": "shadow"
    },
    {
        "id": "C009",
        "name": "ナイト・クローラー",
        "emoji": "👻",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "怪異",
        "region": "1",
        "size": "白くて細い・足だけのような見た目",
        "description": "",
        "image": "assets/uma_night_crawler.png",
        "encounterType": "shadow"
    },
    {
        "id": "C010",
        "name": "ジェヴォーダンのけもの",
        "image": "assets/uma_beast_of_gevaudan.png",
        "emoji": "🐺",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "獣",
        "region": "フランス",
        "size": "1.7",
        "description": "おおかみのような設定",
        "encounterType": "beast"
    },
    {
        "id": "C011",
        "name": "バウオコジ",
        "image": "assets/uma_bauokoji.png",
        "emoji": "👻",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "怪異/こうもり系",
        "region": "コウモリ/サル/犬のような姿と言われる",
        "size": "",
        "description": "",
        "encounterType": "shadow"
    },
    {
        "id": "C012",
        "name": "ジャドーピープル",
        "image": "assets/uma_shadow_people.png",
        "emoji": "👻",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "怪異/ひと型",
        "region": "アメリカ",
        "size": "1.7-2",
        "description": "人を体調不良にしたり家電をゆらす設定",
        "encounterType": "shadow"
    },
    {
        "id": "C013",
        "name": "スレンダーマン",
        "image": "assets/uma_slenderman.png",
        "emoji": "👻",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "怪異/ひと型",
        "region": "1.8-3",
        "size": "背が高く顔や鼻がない設定",
        "description": "",
        "encounterType": "shadow"
    },
    {
        "id": "C014",
        "name": "フラットウッズ・モンスター",
        "emoji": "👻",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "宇宙/怪異",
        "region": "アメリカ",
        "size": "3",
        "description": "大きな目・ヘルメットのような頭",
        "image": "assets/uma_flatwoods_monster.png",
        "encounterType": "shadow"
    },
    {
        "id": "C015",
        "name": "ビッグマン",
        "image": "assets/uma_bigman.png",
        "emoji": "👾",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "ひと型",
        "region": "アメリカ",
        "size": "1.8",
        "description": "体は人間・顔はブタ風",
        "encounterType": "beast"
    },
    {
        "id": "C016",
        "name": "マナナンガル",
        "emoji": "👻",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "怪異/吸血系",
        "region": "フィリピン",
        "size": "夜にコウモリの羽で飛ぶ設定",
        "description": "",
        "encounterType": "shadow"
    },
    {
        "id": "C017",
        "name": "レイク",
        "image": "assets/uma_rake.png",
        "emoji": "👻",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "怪異/ひと型",
        "region": "アメリカ",
        "size": "2",
        "description": "家にしのびこみ泣く人の声など設定",
        "encounterType": "shadow"
    },
    {
        "id": "C018",
        "name": "トロール",
        "image": "assets/uma_troll.png",
        "emoji": "👾",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "小型UMA",
        "region": "0.15-0.5",
        "size": "空中に現れる設定",
        "description": "",
        "encounterType": "beast"
    },
    {
        "id": "C019",
        "name": "ポンベロ",
        "image": "assets/uma_pombero.png",
        "emoji": "👻",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "小人/怪異",
        "region": "0.5",
        "size": "イタズラや家の中に入る設定",
        "description": "",
        "encounterType": "shadow"
    },
    {
        "id": "C020",
        "name": "ドッグマン",
        "emoji": "🐺",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "獣人",
        "region": "アメリカ",
        "size": "1.8-2",
        "description": "犬の頭・二本足で歩く設定",
        "image": "assets/uma_dogman.png",
        "encounterType": "beast"
    },
    {
        "id": "C021",
        "name": "ボスニア・モンスター",
        "image": "assets/uma_bosnian_monster.png",
        "emoji": "🐺",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "獣",
        "region": "ボスニア・ヘルツェゴビナ",
        "size": "0.5",
        "description": "イタチ＋カエルの特徴設定",
        "encounterType": "beast"
    },
    {
        "id": "C022",
        "name": "つばさネコ",
        "image": "assets/uma_winged_cat.png",
        "emoji": "🐱",
        "hp": 15,
        "maxHp": 15,
        "exp": 5,
        "habitat": "まち",
        "type": "動物",
        "region": "世界各地",
        "size": "0.5",
        "description": "鳥のような翼で空を飛ぶネコ",
        "encounterType": "beast"
    },
    {
        "id": "F001",
        "name": "ビッグフット",
        "emoji": "🦶",
        "hp": 25,
        "maxHp": 25,
        "exp": 8,
        "habitat": "森",
        "type": "獣人",
        "region": "アメリカ/カナダ",
        "size": "1.5-4.5",
        "description": "足あとが大きい設定",
        "image": "assets/uma_bigfoot.png",
        "encounterType": "beast"
    },
    {
        "id": "F002",
        "name": "マピンガアリ",
        "image": "assets/uma_mapinguari.png",
        "emoji": "🦍",
        "hp": 25,
        "maxHp": 25,
        "exp": 8,
        "habitat": "森",
        "type": "獣人",
        "region": "ブラジル",
        "size": "1-2",
        "description": "2本足で立って歩く設定",
        "encounterType": "beast"
    },
    {
        "id": "F003",
        "name": "スカンクエイプ",
        "emoji": "🦍",
        "hp": 25,
        "maxHp": 25,
        "exp": 8,
        "habitat": "森",
        "type": "獣人",
        "region": "アメリカ",
        "size": "2",
        "description": "体毛が長い設定",
        "image": "assets/uma_skunk_ape.png",
        "encounterType": "beast"
    },
    {
        "id": "F004",
        "name": "ブキッ・ティマ・モンキーマン",
        "emoji": "🦍",
        "hp": 25,
        "maxHp": 25,
        "exp": 8,
        "habitat": "森",
        "type": "獣人",
        "region": "シンガポール",
        "size": "1-2",
        "description": "森の奥にひそむ設定",
        "encounterType": "beast"
    },
    {
        "id": "F005",
        "name": "オラン・ペンデク",
        "emoji": "🦍",
        "hp": 25,
        "maxHp": 25,
        "exp": 8,
        "habitat": "森",
        "type": "獣人",
        "region": "インドネシア",
        "size": "0.8-1.5",
        "description": "おくびょうで逃げる設定",
        "image": "assets/uma_orang_pendek.png",
        "encounterType": "beast"
    },
    {
        "id": "F006",
        "name": "ベアウルフ",
        "emoji": "🐺",
        "hp": 25,
        "maxHp": 25,
        "exp": 8,
        "habitat": "森",
        "type": "獣人",
        "region": "アメリカ",
        "size": "1.8-2.3",
        "description": "顔はオオカミ・体はクマ設定",
        "image": "assets/uma_bearwolf.png",
        "encounterType": "beast"
    },
    {
        "id": "F007",
        "name": "オラン・ダラム",
        "emoji": "🦍",
        "hp": 25,
        "maxHp": 25,
        "exp": 8,
        "habitat": "森",
        "type": "獣人",
        "region": "マレーシア",
        "size": "1.2-4",
        "description": "ジャングルにひそむ設定",
        "encounterType": "beast"
    },
    {
        "id": "F008",
        "name": "モルガン・ビースト",
        "image": "assets/uma_mogollon_monster.png",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 8,
        "habitat": "森",
        "type": "獣/怪異",
        "region": "アメリカ",
        "size": "白い体・細い手足・光る目設定",
        "description": "",
        "encounterType": "beast"
    },
    {
        "id": "F009",
        "name": "ヒューマノイドがたUMA",
        "emoji": "👾",
        "hp": 25,
        "maxHp": 25,
        "exp": 8,
        "habitat": "森",
        "type": "ひと型",
        "region": "ブラジル",
        "size": "0.5",
        "description": "頭の大きい人のような姿",
        "encounterType": "beast"
    },
    {
        "id": "G001",
        "name": "チュパカブラ",
        "emoji": "🦍",
        "hp": 20,
        "maxHp": 20,
        "exp": 7,
        "habitat": "草原/さばく",
        "type": "怪異/獣人",
        "region": "中南米",
        "size": "0.9-1.2",
        "description": "家畜をおそう設定",
        "image": "assets/uma_chupacabra.png",
        "encounterType": "beast"
    },
    {
        "id": "G002",
        "name": "サーポパード",
        "image": "assets/uma_serpopard.png",
        "emoji": "🐾",
        "hp": 20,
        "maxHp": 20,
        "exp": 7,
        "habitat": "草原/さばく",
        "type": "動物",
        "region": "エジプト/ケニア",
        "size": "首が長くヒョウ顔設定",
        "description": "",
        "encounterType": "beast"
    },
    {
        "id": "G003",
        "name": "スクヴェイダー",
        "image": "assets/uma_skvader.png",
        "emoji": "🐾",
        "hp": 20,
        "maxHp": 20,
        "exp": 7,
        "habitat": "草原/さばく",
        "type": "動物",
        "region": "スウェーデン",
        "size": "0.5-0.8",
        "description": "ウサギ＋鳥の混ざった設定",
        "encounterType": "beast"
    },
    {
        "id": "G004",
        "name": "カーバンクル",
        "image": "assets/uma_carbuncle.png",
        "emoji": "🐾",
        "hp": 20,
        "maxHp": 20,
        "exp": 7,
        "habitat": "草原/さばく",
        "type": "動物/精霊",
        "region": "パラグアイ",
        "size": "0.07-0.10",
        "description": "ひたいの宝石が設定",
        "encounterType": "beast"
    },
    {
        "id": "G005",
        "name": "チバ・フーフィー",
        "emoji": "👻",
        "hp": 20,
        "maxHp": 20,
        "exp": 7,
        "habitat": "草原/さばく",
        "type": "怪異/虫",
        "region": "コンゴ周辺",
        "size": "1.5",
        "description": "タランチュラの巨大版設定",
        "encounterType": "shadow"
    },
    {
        "id": "G006",
        "name": "モシナ",
        "emoji": "👻",
        "hp": 20,
        "maxHp": 20,
        "exp": 7,
        "habitat": "草原/さばく",
        "type": "怪異/ひと型",
        "region": "台湾",
        "size": "1-2",
        "description": "人をさらう設定",
        "encounterType": "shadow"
    },
    {
        "id": "G007",
        "name": "太さい",
        "emoji": "👻",
        "hp": 20,
        "maxHp": 20,
        "exp": 7,
        "habitat": "草原/さばく",
        "type": "怪異",
        "region": "中国",
        "size": "0.3",
        "description": "目がある・せいれい設定",
        "encounterType": "shadow"
    },
    {
        "id": "M001",
        "name": "イエティ",
        "emoji": "🦍",
        "hp": 30,
        "maxHp": 30,
        "exp": 10,
        "habitat": "山",
        "type": "獣人",
        "region": "ヒマラヤ",
        "size": "1.5-6",
        "description": "雪山の生き物として有名",
        "image": "assets/uma_yeti.png",
        "encounterType": "beast"
    },
    {
        "id": "M002",
        "name": "ヨーウィ",
        "emoji": "🦍",
        "hp": 30,
        "maxHp": 30,
        "exp": 10,
        "habitat": "山",
        "type": "獣人",
        "region": "オーストラリア",
        "size": "1.5-3",
        "description": "目はかわいい設定も",
        "image": "assets/uma_yowie.png",
        "encounterType": "beast"
    },
    {
        "id": "M003",
        "name": "モノス",
        "emoji": "🦍",
        "hp": 30,
        "maxHp": 30,
        "exp": 10,
        "habitat": "山",
        "type": "獣人",
        "region": "ベネズエラ",
        "size": "1.5-1.6",
        "description": "谷川で写真が公開された設定",
        "encounterType": "beast"
    },
    {
        "id": "M004",
        "name": "ダッツェルヴルム",
        "emoji": "👻",
        "hp": 30,
        "maxHp": 30,
        "exp": 10,
        "habitat": "山",
        "type": "怪異/獣",
        "region": "アルプス",
        "size": "0.3-2",
        "description": "伝承の生き物",
        "image": "assets/uma_tatzelwurm.png",
        "encounterType": "beast"
    },
    {
        "id": "M005",
        "name": "ゴウロウ",
        "emoji": "👻",
        "hp": 30,
        "maxHp": 30,
        "exp": 10,
        "habitat": "山",
        "type": "怪異/獣",
        "region": "アメリカ",
        "size": "6",
        "description": "山の岩場にひそむ設定",
        "encounterType": "beast"
    },
    {
        "id": "M006",
        "name": "ジェイコブス・クリーチャー",
        "emoji": "👻",
        "hp": 30,
        "maxHp": 30,
        "exp": 10,
        "habitat": "山",
        "type": "怪異/獣",
        "region": "アメリカ",
        "size": "1.5",
        "description": "ビッグフット(8ページ)の子ども説など",
        "encounterType": "beast"
    },
    {
        "id": "S001",
        "name": "ビッグバード",
        "emoji": "🦅",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "鳥",
        "region": "複数国",
        "size": "3-10",
        "description": "つめやくちばしでさらう設定",
        "encounterType": "sky"
    },
    {
        "id": "S002",
        "name": "アフール",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/コウモリ",
        "region": "3-10",
        "size": "大きな翼で飛ぶ設定",
        "description": "",
        "encounterType": "sky"
    },
    {
        "id": "S003",
        "name": "サンダーバード",
        "emoji": "🦅",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "鳥",
        "region": "アメリカ",
        "size": "3-10",
        "description": "でんせつの巨大鳥",
        "image": "assets/uma_thunderbird.png",
        "encounterType": "sky"
    },
    {
        "id": "S004",
        "name": "コンガマトー",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/翼竜",
        "region": "アフリカ",
        "size": "1.5-2",
        "description": "翼竜のような設定",
        "encounterType": "sky"
    },
    {
        "id": "S005",
        "name": "ジーナフォイロ",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/コウモリ",
        "region": "セネガル",
        "size": "1.2",
        "description": "家くらいまで体をかえる設定",
        "encounterType": "sky"
    },
    {
        "id": "S006",
        "name": "オウルマン",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/鳥人",
        "region": "イギリス",
        "size": "1.5-1.7",
        "description": "フクロウのような見た目",
        "image": "assets/uma_owlman.png",
        "encounterType": "sky"
    },
    {
        "id": "S007",
        "name": "オラン・バッチ",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/コウモリ",
        "region": "インドネシア",
        "size": "子どもをさらう設定",
        "description": "",
        "encounterType": "sky"
    },
    {
        "id": "S008",
        "name": "オリチアウ",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/翼竜",
        "region": "カメルーン",
        "size": "大きな翼で山をすべる設定",
        "description": "",
        "encounterType": "sky"
    },
    {
        "id": "S009",
        "name": "ローペン",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/翼竜",
        "region": "パプアニューギニア",
        "size": "1-3",
        "description": "人の死体を食べる設定",
        "encounterType": "sky"
    },
    {
        "id": "S010",
        "name": "ガーゴイル",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異",
        "region": "プエルトリコ",
        "size": "チュパカブラ(9ページ)と同じ説も",
        "description": "",
        "encounterType": "sky"
    },
    {
        "id": "S011",
        "name": "フライング・ヒューマノイド",
        "image": "assets/uma_flying_humanoid.png",
        "emoji": "👾",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "ひと型",
        "region": "複数国",
        "size": "1-3",
        "description": "空から降りて襲う設定",
        "encounterType": "sky"
    },
    {
        "id": "S012",
        "name": "フライング・ホース",
        "emoji": "🐾",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "動物",
        "region": "イタリア/米国/メキシコ",
        "size": "動画にとられたが謎が多い設定",
        "description": "",
        "encounterType": "sky"
    },
    {
        "id": "S013",
        "name": "フライング・ワーム",
        "emoji": "🐛",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/虫",
        "region": "世界各地",
        "size": "1-10",
        "description": "空を飛ぶ虫のような設定",
        "encounterType": "sky"
    },
    {
        "id": "S014",
        "name": "ライト・ビーイング",
        "image": "assets/uma_light_being.png",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/発光",
        "region": "光る存在の設定",
        "size": "",
        "description": "",
        "encounterType": "sky"
    },
    {
        "id": "S015",
        "name": "スカイフィッシュ",
        "emoji": "🐟",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異",
        "region": "世界各地",
        "size": "0.3-30",
        "description": "日本の映像でも話題になった設定",
        "encounterType": "sky"
    },
    {
        "id": "S016",
        "name": "フライング・サーペント",
        "emoji": "🐍",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/ヘビ",
        "region": "メキシコ/米国",
        "size": "5",
        "description": "体をくねらせ空をただよう設定",
        "encounterType": "sky"
    },
    {
        "id": "S017",
        "name": "オヨ・フリオ",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/巨大いもむし",
        "region": "メキシコ",
        "size": "25-30",
        "description": "巨大イモムシの姿で空を飛ぶ設定",
        "encounterType": "sky"
    },
    {
        "id": "S018",
        "name": "ドラゴン",
        "emoji": "🐉",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異/竜",
        "region": "昔の空想生物として紹介されることも",
        "size": "",
        "description": "",
        "encounterType": "sky"
    },
    {
        "id": "S019",
        "name": "フライング・ストリングス",
        "emoji": "👻",
        "hp": 25,
        "maxHp": 25,
        "exp": 9,
        "habitat": "空",
        "type": "怪異",
        "region": "メキシコ",
        "size": "黒い糸のようなものを吐く設定",
        "description": "",
        "encounterType": "sky"
    },
    {
        "id": "O001",
        "name": "クラーケン",
        "emoji": "🦑",
        "hp": 40,
        "maxHp": 40,
        "exp": 12,
        "habitat": "海",
        "type": "海の怪物",
        "region": "世界各地",
        "size": "20-60",
        "description": "巨大イカ/タコのような設定",
        "image": "assets/uma_kraken.png",
        "encounterType": "water"
    },
    {
        "id": "O002",
        "name": "シーサーペント",
        "emoji": "🐍",
        "hp": 40,
        "maxHp": 40,
        "exp": 12,
        "habitat": "海",
        "type": "海の怪物",
        "region": "世界各地",
        "size": "15-60",
        "description": "大むかしから目撃が多い設定",
        "encounterType": "water"
    },
    {
        "id": "O003",
        "name": "ニンゲン",
        "image": "assets/uma_ningen.png",
        "emoji": "👻",
        "hp": 40,
        "maxHp": 40,
        "exp": 12,
        "habitat": "海",
        "type": "怪異/人型",
        "region": "北極/南極",
        "size": "10-20",
        "description": "白い体・手はひれ設定",
        "encounterType": "water"
    },
    {
        "id": "O004",
        "name": "グロブスター",
        "emoji": "👻",
        "hp": 40,
        "maxHp": 40,
        "exp": 12,
        "habitat": "海",
        "type": "怪異",
        "region": "世界各地",
        "size": "6-24",
        "description": "毛のようなもの・正体不明設定",
        "encounterType": "water"
    },
    {
        "id": "O005",
        "name": "モーガウル",
        "emoji": "🦑",
        "hp": 40,
        "maxHp": 40,
        "exp": 12,
        "habitat": "海",
        "type": "海の怪物",
        "region": "イギリス",
        "size": "4-18",
        "description": "首が長い海の怪物設定",
        "encounterType": "water"
    },
    {
        "id": "O006",
        "name": "キャディ",
        "emoji": "🦑",
        "hp": 40,
        "maxHp": 40,
        "exp": 12,
        "habitat": "海",
        "type": "海の怪物",
        "region": "カナダ",
        "size": "9-15",
        "description": "首にたてがみ設定",
        "encounterType": "water"
    },
    {
        "id": "O007",
        "name": "ブランッキー",
        "emoji": "🦑",
        "hp": 40,
        "maxHp": 40,
        "exp": 12,
        "habitat": "海",
        "type": "海の怪物",
        "region": "黒海",
        "size": "10-40",
        "description": "昔からの目撃・記録設定",
        "encounterType": "water"
    },
    {
        "id": "O008",
        "name": "ニューネッシー",
        "emoji": "🦑",
        "hp": 40,
        "maxHp": 40,
        "exp": 12,
        "habitat": "海",
        "type": "海の怪物",
        "region": "ニュージーランド",
        "size": "10",
        "description": "1977年に死体が見つかった設定",
        "encounterType": "water"
    },
    {
        "id": "O009",
        "name": "ニンポー",
        "emoji": "👻",
        "hp": 40,
        "maxHp": 40,
        "exp": 12,
        "habitat": "海",
        "type": "怪異/水棲",
        "region": "中国",
        "size": "12",
        "description": "頭に角・毛がある設定",
        "encounterType": "water"
    },
    {
        "id": "L001",
        "name": "ネッシー",
        "emoji": "🦕",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "湖の怪物",
        "region": "イギリス",
        "size": "10-12",
        "description": "ネス湖で有名",
        "image": "assets/uma_nessie.png",
        "encounterType": "water"
    },
    {
        "id": "L002",
        "name": "オゴポゴ",
        "emoji": "🦕",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "湖の怪物",
        "region": "カナダ",
        "size": "5-10",
        "description": "顔が馬やヤギに似る設定",
        "encounterType": "water"
    },
    {
        "id": "L003",
        "name": "マニポゴ",
        "emoji": "🦕",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "湖の怪物",
        "region": "カナダ",
        "size": "5-12",
        "description": "細長い体を上下にくねらせる設定",
        "encounterType": "water"
    },
    {
        "id": "L004",
        "name": "ゾデンデキ",
        "emoji": "🦕",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "湖の怪物",
        "region": "コンゴ",
        "size": "5-8",
        "description": "こうらと丸み・長さ4-5m設定",
        "encounterType": "water"
    },
    {
        "id": "L005",
        "name": "チェナリバー・アイスモンスター",
        "emoji": "👻",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "怪異",
        "region": "アメリカ",
        "size": "5",
        "description": "こおりがついたままの見た目設定",
        "encounterType": "water"
    },
    {
        "id": "L006",
        "name": "フロッグマン",
        "emoji": "🦍",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "獣人",
        "region": "アメリカ",
        "size": "1.2",
        "description": "ぬめぬめ・川に出る設定",
        "image": "assets/uma_frogman.png",
        "encounterType": "water"
    },
    {
        "id": "L007",
        "name": "ドアーチュ",
        "emoji": "👻",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "怪異",
        "region": "アイルランド",
        "size": "2-3",
        "description": "水かき・泳ぎが得意設定",
        "encounterType": "water"
    },
    {
        "id": "L008",
        "name": "ナーカ",
        "emoji": "👻",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "怪異/ヘビ",
        "region": "東南アジア",
        "size": "10-70",
        "description": "大きなヘビ・角がある設定",
        "encounterType": "water"
    },
    {
        "id": "L009",
        "name": "ラウ",
        "emoji": "👻",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "動物/怪異",
        "region": "アフリカ",
        "size": "12-30",
        "description": "太いどう体の設定",
        "encounterType": "water"
    },
    {
        "id": "L010",
        "name": "バビア・ビースト",
        "emoji": "🦍",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "獣人",
        "region": "ブラジル",
        "size": "1.5-2",
        "description": "角がある・武器を持つ設定",
        "encounterType": "water"
    },
    {
        "id": "L011",
        "name": "セルマ",
        "emoji": "🦕",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "湖の怪物",
        "region": "ノルウェー",
        "size": "6-10",
        "description": "鳴き声のような音設定",
        "encounterType": "water"
    },
    {
        "id": "L012",
        "name": "モケーレ・ムベンベ",
        "emoji": "🦕",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "湖の怪物",
        "region": "コンゴ",
        "size": "8-15",
        "description": "恐竜のような姿設定",
        "encounterType": "water"
    },
    {
        "id": "L013",
        "name": "メンフレ",
        "emoji": "🦕",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "湖の怪物",
        "region": "アメリカ",
        "size": "6-15",
        "description": "湖にすむ恐れられる設定",
        "encounterType": "water"
    },
    {
        "id": "L014",
        "name": "チャンプ",
        "emoji": "🦕",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "湖の怪物",
        "region": "アメリカ",
        "size": "4.5-18",
        "description": "首が長い・写真の真偽議論",
        "encounterType": "water"
    },
    {
        "id": "L015",
        "name": "ナウエリート",
        "emoji": "🦕",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "湖の怪物",
        "region": "アイルランド",
        "size": "5-20",
        "description": "長い首・中にはこぶ設定",
        "encounterType": "water"
    },
    {
        "id": "L016",
        "name": "スクリムスル",
        "emoji": "🦕",
        "hp": 35,
        "maxHp": 35,
        "exp": 11,
        "habitat": "湖/川",
        "type": "湖の怪物",
        "region": "アイスランド",
        "size": "14",
        "description": "長い尾でうずまき設定",
        "encounterType": "water"
    },
    {
        "id": "R001",
        "name": "モンゴリアン・デスワーム",
        "emoji": "🐛",
        "hp": 50,
        "maxHp": 50,
        "exp": 15,
        "habitat": "危険ランキング",
        "type": "怪異/虫",
        "region": "モンゴル",
        "size": "0.5-1.2",
        "description": "電気を出す設定",
        "encounterType": "shadow"
    },
    {
        "id": "R002",
        "name": "ピアサバード",
        "emoji": "🦅",
        "hp": 50,
        "maxHp": 50,
        "exp": 15,
        "habitat": "危険ランキング",
        "type": "怪異/鳥",
        "region": "村をおそう設定",
        "size": "",
        "description": "",
        "encounterType": "shadow"
    },
    {
        "id": "R003",
        "name": "ジェヴォーダンのけもの",
        "emoji": "🐺",
        "hp": 50,
        "maxHp": 50,
        "exp": 15,
        "habitat": "危険ランキング",
        "type": "獣",
        "region": "フランス",
        "size": "(C010と同じ)",
        "description": "",
        "encounterType": "beast"
    },
    {
        "id": "R004",
        "name": "モスマン",
        "emoji": "👻",
        "hp": 50,
        "maxHp": 50,
        "exp": 15,
        "habitat": "危険ランキング",
        "type": "怪異/ひと型",
        "region": "(C001と同じ)",
        "size": "",
        "description": "",
        "encounterType": "shadow"
    },
    {
        "id": "R005",
        "name": "ネスキ",
        "emoji": "🦕",
        "hp": 50,
        "maxHp": 50,
        "exp": 15,
        "habitat": "危険ランキング",
        "type": "湖の怪物",
        "region": "ロシア",
        "size": "6-20",
        "description": "湖にひきずりこむ設定",
        "encounterType": "beast"
    }
];